FROM nginx

# Установка Git для клонирования
RUN apt-get update && apt-get install -y git

# Установка рабочей директории
WORKDIR /usr/share/nginx/html

# Клонирование репозитория
RUN git clone https://github.com/Sashmolod/vizitka.git .

# Копирование конфигурации Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 8010
