version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    container_name: my_server
    ports:
      - "3050:3050"
    networks:
      - my_network
    restart: unless-stopped
    volumes:
      - ./server:/var/www/vizitka/server

  client:
    build:
      context: .
      dockerfile: Dockerfile-client
    container_name: my_client
    ports:
      - "8010:80"
    networks:
      - my_network
    restart: unless-stopped
    volumes:
      - ./client:/var/www/vizitka/client

networks:
  my_network:
    driver: bridge
