version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    container_name: my_server
    ports:
      - "3050:3050"

  client:
    build:
      context: .
      dockerfile: Dockerfile-client
    container_name: my_client
    ports:
      - "8010:80"
