version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    container_name: my_server
    ports:
      - "3050:3050"
    volumes:
      - /var/www/vizitka/server:/var/www/vizitka/server
    networks:
      - my_network
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: Dockerfile-client
    container_name: my_client
    ports:
      - "8010:80"
    volumes:
      - /var/www/vizitka/client:/usr/share/nginx/html
    networks:
      - my_network
    restart: unless-stopped

networks:
  my_network:
    driver: bridge
