FROM node:14

# Установка Git из стандартного репозитория
RUN apt-get update && \
    apt-get install -y git && \
    apt-get clean

# Установка рабочей директории
WORKDIR /usr/src/server

# Клонирование репозитория
RUN git clone --no-checkout https://github.com/Sashmolod/vizitka.git .

# Инициализация sparse-checkout и выбор нужной папки
RUN git sparse-checkout init --cone && \
    git sparse-checkout set server && \
    git checkout master

# Установка зависимостей
COPY package*.json ./
RUN npm install

EXPOSE 3050

CMD ["node", "server.js"]
